<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\AzureBlobSearch.Application\AzureBlobSearch.Application.csproj" />
    <ProjectReference Include="..\AzureBlobSearch.Infrastructure\AzureBlobSearch.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>
</Project>
