<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\AzureBlobSearch.Application\AzureBlobSearch.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Search.Documents" Version="11.7.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
  </ItemGroup>
</Project>

